# Generated by Django 4.2.25 on 2025-10-29 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('container_width', models.FloatField()),
                ('container_height', models.FloatField()),
                ('input_rectangles', models.JSONField()),
                ('packed_rectangles', models.JSONField()),
                ('visualization_data', models.JSONField()),
                ('success', models.BooleanField()),
                ('density', models.FloatField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_reports', to='projects.project')),
            ],
            options={
                'verbose_name': 'گزارش بهینه\u200cسازی چیدمان',
                'verbose_name_plural': 'گزارش\u200cهای بهینه\u200cسازی چیدمان',
                'ordering': ['-created_at'],
            },
        ),
    ]
