# Generated by Django 4.2.25 on 2025-10-29 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_packingreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinPackingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام گزارش')),
                ('container_width', models.FloatField(verbose_name='عرض ورق')),
                ('container_height', models.FloatField(verbose_name='ارتفاع ورق')),
                ('rectangles', models.JSONField(verbose_name='قطعات')),
                ('packed_rectangles', models.JSONField(verbose_name='قطعات چیده شده')),
                ('visualization', models.JSONField(verbose_name='داده\u200cهای بصری')),
                ('density', models.FloatField(verbose_name='چگالی')),
                ('success', models.BooleanField(verbose_name='موفقیت')),
                ('message', models.TextField(blank=True, verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bin_packing_reports', to='projects.project')),
            ],
            options={
                'verbose_name': 'گزارش بهینه\u200cسازی چیدمان',
                'verbose_name_plural': 'گزارش\u200cهای بهینه\u200cسازی چیدمان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PackingReport',
        ),
    ]
